@baseUrl = deploy-recode.vercel.app
###http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwOTgwNjJlLWMxNmYtNGQxYi05YTlkLTc1OGIwYTIzMjNkZSIsImFkbWluIjp0cnVlLCJzdWJBZG1pbiI6ZmFsc2UsImlhdCI6MTc1NjQzNDY0NywiZXhwIjoxNzU2NTIxMDQ3fQ.Unski6Yn8j6qOo-kR7IqG_3p3NBsMZFnfVh1iTFFaqQ

###Rota de teste
GET {{baseUrl}}/

### Criar usuario
POST {{baseUrl}}/register
Content-Type: application/json

{
  "nick": "usuario9878800",
  "name": "Lucas",
  "surname": "Neto",
  "email": "lucas.088silva@email.com",
  "senha": "senhaSegura123",
  "instituicao": 1
}

### Login usuario
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "gabriela@edu.ufrgs.com.br",
  "password": "admin12345"
}

### Buscar usuario 
GET {{baseUrl}}/user/profile
Content-Type: application/json
Authorization: Bearer {{token}}


### Teste de rota de porto
GET {{baseUrl}}/user/pendingport
Content-Type: application/json
Authorization: Bearer {{token}}